name: Extraction
version: 1.0.0

config:
  settings:
    include_event_name_in_code: true
  data:
    # - name: eicu-demo
      # version: "2.0"
      # path: /home/q039tl/physionet.org/files/eicu-crd-demo/2.0
    # - name: mimic-iv-demo
      # version: "2.2"
      # path: /home/q039tl/physionet.org/files/mimiciv-demo/2.2
    # - name: eicu-crd
      # version: "2.0"
      # path: /home/q039tl/physionet.org/files/eicu-crd/2.0
    - name: mimic-iv
      version: "3.1"
      path: /home/q039tl/physionet.org/files/mimiciv/3.1
    # - name: nwicu
    #   version: "0.1.0"
    #   path: /home/q039tl/physionet.org/files/nwicu/0.1.0
